"""application baseline."""

from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20261002_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("subject", name=op.f("uq_users_subject")),
        schema="app",
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("active_run_id", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_message_order", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'purging')", name=op.f("ck_conversations_status")),
        sa.CheckConstraint(
            "(active_run_id IS NULL) = (lease_until IS NULL)",
            name=op.f("ck_conversations_lease_pair"),
        ),
        sa.CheckConstraint("next_message_order > 0", name=op.f("ck_conversations_message_order")),
        sa.ForeignKeyConstraint(
            ["active_run_id", "id"],
            ["app.agent_runs.id", "app.agent_runs.conversation_id"],
            name="fk_conversations_active_run",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app.users.id"], name=op.f("fk_conversations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_conversations_id_user_id")),
        schema="app",
    )
    op.create_index(
        "ix_conversations_owner_activity",
        "conversations",
        ["user_id", "last_activity_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_conversations_retention",
        "conversations",
        ["status", "last_activity_at"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("visibility", sa.Text(), server_default="private", nullable=False),
        sa.Column("lifecycle", sa.Text(), server_default="live", nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("file_type", sa.Text(), nullable=False),
        sa.Column("published_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(filename) <> ''", name=op.f("ck_documents_filename")),
        sa.CheckConstraint("file_type IN ('pdf', 'docx')", name=op.f("ck_documents_file_type")),
        sa.CheckConstraint(
            "lifecycle IN ('live', 'deleting', 'deleted')", name=op.f("ck_documents_lifecycle")
        ),
        sa.CheckConstraint(
            "visibility IN ('private', 'shared')", name=op.f("ck_documents_visibility")
        ),
        sa.ForeignKeyConstraint(
            ["published_version_id", "id"],
            ["app.document_versions.id", "app.document_versions.document_id"],
            name="fk_documents_published_version",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app.users.id"], name=op.f("fk_documents_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        schema="app",
    )
    op.create_index(
        "ix_documents_visibility",
        "documents",
        ["user_id", "visibility", "lifecycle"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "document_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("pipeline_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("object_version_id", sa.Text(), nullable=False),
        sa.Column("embedding_model_id", sa.Text(), nullable=False),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('candidate', 'published', 'superseded', 'failed')",
            name=op.f("ck_document_versions_status"),
        ),
        sa.CheckConstraint(
            "embedding_dimensions = 1024", name=op.f("ck_document_versions_embedding_dimensions")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["app.documents.id"],
            name=op.f("fk_document_versions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint("id", "document_id", name=op.f("uq_document_versions_id_document_id")),
        schema="app",
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("request_key", sa.Text(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("user_message_id", sa.Uuid(), nullable=False),
        sa.Column("user_role", sa.Text(), server_default="user", nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'completed', 'failed')", name=op.f("ck_turns_status")
        ),
        sa.CheckConstraint("user_role = 'user'", name=op.f("ck_turns_user_role")),
        sa.CheckConstraint(
            "char_length(request_key) BETWEEN 1 AND 200", name=op.f("ck_turns_request_key")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id", "user_id"],
            ["app.conversations.id", "app.conversations.user_id"],
            name=op.f("fk_turns_conversation_id_user_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["app.conversations.id"],
            name=op.f("fk_turns_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_message_id", "id", "conversation_id", "user_role"],
            [
                "app.messages.id",
                "app.messages.turn_id",
                "app.messages.conversation_id",
                "app.messages.role",
            ],
            name="fk_turns_user_message",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
        sa.UniqueConstraint("id", "conversation_id", name=op.f("uq_turns_id_conversation_id")),
        sa.UniqueConstraint(
            "user_id",
            "conversation_id",
            "request_key",
            name=op.f("uq_turns_user_id_conversation_id_request_key"),
        ),
        schema="app",
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("file_type", sa.Text(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("section_heading", sa.Text(), nullable=True),
        sa.Column(
            "locators", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("embedding_model_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(filename) <> '' AND btrim(text) <> ''",
            name=op.f("ck_document_chunks_required_metadata"),
        ),
        sa.CheckConstraint(
            "file_type IN ('pdf', 'docx')", name=op.f("ck_document_chunks_file_type")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(locators) = 'array'", name=op.f("ck_document_chunks_locators_array")
        ),
        sa.CheckConstraint(
            "status <> 'completed' OR embedding IS NOT NULL",
            name=op.f("ck_document_chunks_completed_embedding"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'retrying', 'completed', 'failed')",
            name=op.f("ck_document_chunks_status"),
        ),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_document_chunks_ordinal")),
        sa.CheckConstraint("page IS NULL OR page > 0", name=op.f("ck_document_chunks_page")),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["app.document_versions.id"],
            name=op.f("fk_document_chunks_version_id_document_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "version_id", "ordinal", name=op.f("uq_document_chunks_version_id_ordinal")
        ),
        schema="app",
    )
    op.create_index(
        "ix_document_chunks_embedding",
        "document_chunks",
        ["embedding"],
        unique=False,
        schema="app",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "sources", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("message_order", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(role = 'user' AND attempt_number = 0 AND status = 'completed') OR (role = 'assistant' AND attempt_number > 0)",
            name=op.f("ck_messages_attempt"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(sources) = 'array'", name=op.f("ck_messages_sources_array")
        ),
        sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f("ck_messages_role")),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'failed')", name=op.f("ck_messages_status")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["app.conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["turn_id", "conversation_id"],
            ["app.turns.id", "app.turns.conversation_id"],
            name=op.f("fk_messages_turn_id_conversation_id_turns"),
            ondelete="CASCADE",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "conversation_id",
            "message_order",
            name=op.f("uq_messages_conversation_id_message_order"),
        ),
        sa.UniqueConstraint("id", "conversation_id", name=op.f("uq_messages_id_conversation_id")),
        sa.UniqueConstraint(
            "id",
            "turn_id",
            "conversation_id",
            "role",
            name=op.f("uq_messages_id_turn_id_conversation_id_role"),
        ),
        sa.UniqueConstraint(
            "turn_id",
            "role",
            "attempt_number",
            name=op.f("uq_messages_turn_id_role_attempt_number"),
        ),
        schema="app",
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=False),
        sa.Column("user_message_id", sa.Uuid(), nullable=False),
        sa.Column("user_role", sa.Text(), server_default="user", nullable=False),
        sa.Column("assistant_message_id", sa.Uuid(), nullable=False),
        sa.Column("assistant_role", sa.Text(), server_default="assistant", nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("root_span_id", sa.String(length=16), nullable=False),
        sa.Column("base_checkpoint_id", sa.Text(), nullable=True),
        sa.Column("checkpoint_prepared", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("failure_category", sa.Text(), nullable=True),
        sa.Column("retry_of_run_id", sa.Uuid(), nullable=True),
        sa.Column("agent_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("retrieval_version", sa.String(length=64), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'failed' AND failure_category IS NOT NULL) OR (status <> 'failed' AND failure_category IS NULL)",
            name=op.f("ck_agent_runs_failure"),
        ),
        sa.CheckConstraint(
            "(status = 'pending' AND ended_at IS NULL) OR (status <> 'pending' AND ended_at IS NOT NULL)",
            name=op.f("ck_agent_runs_terminal_time"),
        ),
        sa.CheckConstraint(
            "root_span_id ~ '^[0-9a-f]{16}$' AND root_span_id <> repeat('0',16)",
            name=op.f("ck_agent_runs_root_span_id"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'failed')", name=op.f("ck_agent_runs_status")
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0',32)",
            name=op.f("ck_agent_runs_trace_id"),
        ),
        sa.CheckConstraint(
            "user_role = 'user' AND assistant_role = 'assistant'", name=op.f("ck_agent_runs_roles")
        ),
        sa.CheckConstraint("attempt_number > 0", name=op.f("ck_agent_runs_attempt")),
        sa.ForeignKeyConstraint(
            ["assistant_message_id", "turn_id", "conversation_id", "assistant_role"],
            [
                "app.messages.id",
                "app.messages.turn_id",
                "app.messages.conversation_id",
                "app.messages.role",
            ],
            name=op.f(
                "fk_agent_runs_assistant_message_id_turn_id_conversation_id_assistant_role_messages"
            ),
            ondelete="CASCADE",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["app.conversations.id"],
            name=op.f("fk_agent_runs_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["retry_of_run_id", "turn_id", "conversation_id"],
            ["app.agent_runs.id", "app.agent_runs.turn_id", "app.agent_runs.conversation_id"],
            name=op.f("fk_agent_runs_retry_of_run_id_turn_id_conversation_id_agent_runs"),
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["turn_id", "conversation_id"],
            ["app.turns.id", "app.turns.conversation_id"],
            name=op.f("fk_agent_runs_turn_id_conversation_id_turns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_message_id", "turn_id", "conversation_id", "user_role"],
            [
                "app.messages.id",
                "app.messages.turn_id",
                "app.messages.conversation_id",
                "app.messages.role",
            ],
            name=op.f("fk_agent_runs_user_message_id_turn_id_conversation_id_user_role_messages"),
            ondelete="CASCADE",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
        sa.UniqueConstraint(
            "assistant_message_id", name=op.f("uq_agent_runs_assistant_message_id")
        ),
        sa.UniqueConstraint("id", "conversation_id", name=op.f("uq_agent_runs_id_conversation_id")),
        sa.UniqueConstraint(
            "id",
            "turn_id",
            "conversation_id",
            name=op.f("uq_agent_runs_id_turn_id_conversation_id"),
        ),
        sa.UniqueConstraint(
            "turn_id", "attempt_number", name=op.f("uq_agent_runs_turn_id_attempt_number")
        ),
        schema="app",
    )
    op.create_index(
        "ix_agent_runs_conversation_started",
        "agent_runs",
        ["conversation_id", "started_at"],
        unique=False,
        schema="app",
    )
    op.create_index("ix_agent_runs_trace", "agent_runs", ["trace_id"], unique=False, schema="app")
    op.create_table(
        "message_feedback",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("assistant_message_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating = 'dislike' OR comment IS NULL",
            name=op.f("ck_message_feedback_dislike_comment"),
        ),
        sa.CheckConstraint(
            "rating IN ('like', 'dislike')", name=op.f("ck_message_feedback_rating")
        ),
        sa.CheckConstraint(
            "comment IS NULL OR char_length(comment) BETWEEN 1 AND 4000",
            name=op.f("ck_message_feedback_comment_length"),
        ),
        sa.ForeignKeyConstraint(
            ["assistant_message_id", "conversation_id"],
            ["app.messages.id", "app.messages.conversation_id"],
            name=op.f("fk_message_feedback_assistant_message_id_conversation_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id", "user_id"],
            ["app.conversations.id", "app.conversations.user_id"],
            name=op.f("fk_message_feedback_conversation_id_user_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "assistant_message_id", name=op.f("pk_message_feedback")
        ),
        schema="app",
    )
    op.create_table(
        "retry_requests",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("request_key", sa.Text(), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=False),
        sa.Column("expected_run_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(request_key) BETWEEN 1 AND 200", name=op.f("ck_retry_requests_request_key")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_run_id", "turn_id", "conversation_id"],
            ["app.agent_runs.id", "app.agent_runs.turn_id", "app.agent_runs.conversation_id"],
            name=op.f("fk_retry_requests_assigned_run_id_turn_id_conversation_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id", "user_id"],
            ["app.conversations.id", "app.conversations.user_id"],
            name=op.f("fk_retry_requests_conversation_id_user_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["expected_run_id", "turn_id", "conversation_id"],
            ["app.agent_runs.id", "app.agent_runs.turn_id", "app.agent_runs.conversation_id"],
            name=op.f("fk_retry_requests_expected_run_id_turn_id_conversation_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "conversation_id", "request_key", name=op.f("pk_retry_requests")
        ),
        schema="app",
    )
    op.create_table(
        "thread_feedback",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("context_run_id", sa.Uuid(), nullable=True),
        sa.Column("context_message_order", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating IS NOT NULL OR (comment IS NOT NULL AND btrim(comment) <> '')",
            name=op.f("ck_thread_feedback_has_value"),
        ),
        sa.CheckConstraint(
            "rating IS NULL OR rating IN ('like', 'dislike')",
            name=op.f("ck_thread_feedback_rating"),
        ),
        sa.CheckConstraint(
            "comment IS NULL OR char_length(comment) BETWEEN 1 AND 4000",
            name=op.f("ck_thread_feedback_comment_length"),
        ),
        sa.CheckConstraint(
            "context_message_order >= 0", name=op.f("ck_thread_feedback_context_order")
        ),
        sa.ForeignKeyConstraint(
            ["context_run_id", "conversation_id"],
            ["app.agent_runs.id", "app.agent_runs.conversation_id"],
            name=op.f("fk_thread_feedback_context_run_id_conversation_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id", "user_id"],
            ["app.conversations.id", "app.conversations.user_id"],
            name=op.f("fk_thread_feedback_conversation_id_user_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "conversation_id", name=op.f("pk_thread_feedback")),
        schema="app",
    )
    # ### end Alembic commands ###

    # Cyclic references must be attached after both tables exist.
    op.create_foreign_key(
        "fk_turns_user_message",
        "turns",
        "messages",
        ["user_message_id", "id", "conversation_id", "user_role"],
        ["id", "turn_id", "conversation_id", "role"],
        source_schema="app",
        referent_schema="app",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_conversations_active_run",
        "conversations",
        "agent_runs",
        ["active_run_id", "id"],
        ["id", "conversation_id"],
        source_schema="app",
        referent_schema="app",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_documents_published_version",
        "documents",
        "document_versions",
        ["published_version_id", "id"],
        ["id", "document_id"],
        source_schema="app",
        referent_schema="app",
        deferrable=True,
        initially="DEFERRED",
    )


def downgrade() -> None:
    raise RuntimeError("Baseline downgrade is destructive; restore a database backup instead.")
