"""document ingestion work state."""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20261002_0002"
down_revision: str | None = "20261002_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor_permits",
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(token IS NULL) = (lease_until IS NULL)", name=op.f("ck_vendor_permits_lease_pair")
        ),
        sa.CheckConstraint("slot > 0", name=op.f("ck_vendor_permits_slot")),
        sa.PrimaryKeyConstraint("slot", name=op.f("pk_vendor_permits")),
        schema="app",
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("stage", sa.Text(), server_default="extraction", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cycle_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("retry_cycle", sa.Integer(), server_default="0", nullable=False),
        sa.Column("generation", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "next_retry_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("error_category", sa.Text(), nullable=True),
        sa.Column("total_chunks", sa.Integer(), nullable=True),
        sa.Column(
            "trace_context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind = 'delete' OR version_id IS NOT NULL",
            name=op.f("ck_ingestion_jobs_version_required"),
        ),
        sa.CheckConstraint(
            "kind IN ('index', 'delete', 'superseded_cleanup')", name=op.f("ck_ingestion_jobs_kind")
        ),
        sa.CheckConstraint(
            "stage IN ('extraction', 'embedding', 'publication', 'cleanup', 'done')",
            name=op.f("ck_ingestion_jobs_stage"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'processing', 'retrying', 'ready', 'failed', 'cancelled')",
            name=op.f("ck_ingestion_jobs_status"),
        ),
        sa.CheckConstraint(
            "(lease_owner IS NULL) = (lease_until IS NULL)",
            name=op.f("ck_ingestion_jobs_lease_pair"),
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND cycle_attempts >= 0 AND generation >= 0",
            name=op.f("ck_ingestion_jobs_counters"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["app.documents.id"],
            name=op.f("fk_ingestion_jobs_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["app.document_versions.id"],
            name=op.f("fk_ingestion_jobs_version_id_document_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
        schema="app",
    )
    op.create_index(
        "ix_ingestion_jobs_due",
        "ingestion_jobs",
        ["next_retry_at", "lease_until"],
        unique=False,
        schema="app",
        postgresql_where=sa.text("status IN ('queued', 'processing', 'retrying')"),
    )
    op.create_index(
        "uq_ingestion_jobs_active_index",
        "ingestion_jobs",
        ["document_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text(
            "kind = 'index' AND status IN ('queued', 'processing', 'retrying')"
        ),
    )
    op.create_index(
        "uq_ingestion_jobs_delete",
        "ingestion_jobs",
        ["document_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("kind = 'delete'"),
    )
    op.create_index(
        "uq_ingestion_jobs_index_version",
        "ingestion_jobs",
        ["version_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("kind = 'index'"),
    )
    op.create_table(
        "upload_requests",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("request_key", sa.Text(), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(request_key) BETWEEN 1 AND 200",
            name=op.f("ck_upload_requests_request_key"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["app.documents.id"],
            name=op.f("fk_upload_requests_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["app.ingestion_jobs.id"],
            name=op.f("fk_upload_requests_job_id_ingestion_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app.users.id"], name=op.f("fk_upload_requests_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["app.document_versions.id"],
            name=op.f("fk_upload_requests_version_id_document_versions"),
        ),
        sa.PrimaryKeyConstraint("user_id", "request_key", name=op.f("pk_upload_requests")),
        schema="app",
    )
    op.add_column(
        "document_chunks",
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        schema="app",
    )
    op.add_column(
        "document_chunks", sa.Column("start_offset", sa.Integer(), nullable=True), schema="app"
    )
    op.add_column(
        "document_chunks", sa.Column("end_offset", sa.Integer(), nullable=True), schema="app"
    )
    op.add_column(
        "document_chunks",
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        schema="app",
    )
    op.add_column(
        "document_chunks",
        sa.Column("cycle_attempts", sa.Integer(), server_default="0", nullable=False),
        schema="app",
    )
    op.add_column(
        "document_chunks",
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        schema="app",
    )
    op.add_column(
        "document_chunks", sa.Column("error_category", sa.Text(), nullable=True), schema="app"
    )
    op.add_column("document_versions", sa.Column("user_id", sa.Uuid(), nullable=True), schema="app")
    op.add_column(
        "document_versions",
        sa.Column("corpus", sa.Text(), server_default="", nullable=False),
        schema="app",
    )
    op.add_column(
        "document_versions",
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        schema="app",
    )
    op.add_column(
        "document_versions",
        sa.Column(
            "pipeline_configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        schema="app",
    )
    op.add_column(
        "document_versions",
        sa.Column("manifest_complete", sa.Boolean(), server_default="false", nullable=False),
        schema="app",
    )
    op.add_column(
        "document_versions", sa.Column("filename", sa.Text(), nullable=True), schema="app"
    )
    op.add_column(
        "document_versions", sa.Column("file_type", sa.Text(), nullable=True), schema="app"
    )
    op.add_column("document_versions", sa.Column("title", sa.Text(), nullable=True), schema="app")
    op.add_column(
        "document_versions",
        sa.Column(
            "project_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        schema="app",
    )
    op.alter_column(
        "document_versions", "object_key", existing_type=sa.TEXT(), nullable=True, schema="app"
    )
    op.alter_column(
        "document_versions",
        "object_version_id",
        existing_type=sa.TEXT(),
        nullable=True,
        schema="app",
    )
    op.create_index(
        "uq_document_versions_live_content",
        "document_versions",
        ["user_id", "corpus", "sha256", "pipeline_fingerprint"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("retired_at IS NULL"),
    )
    op.create_foreign_key(
        op.f("fk_document_versions_user_id_users"),
        "document_versions",
        "users",
        ["user_id"],
        ["id"],
        source_schema="app",
        referent_schema="app",
    )
    op.add_column(
        "documents",
        sa.Column(
            "project_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        schema="app",
    )
    op.alter_column("documents", "filename", existing_type=sa.TEXT(), nullable=True, schema="app")
    op.alter_column("documents", "file_type", existing_type=sa.TEXT(), nullable=True, schema="app")
    op.execute("""UPDATE app.document_versions v SET user_id = d.user_id,
        filename = d.filename, file_type = d.file_type, title = d.title,
        project_metadata = d.project_metadata FROM app.documents d WHERE v.document_id = d.id""")
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Baseline downgrade is destructive; restore a database backup instead.")
